#!/usr/bin/env ruby

def line(m)
  puts '-' * 5 + " #{m} " + '-' * 60
end

def show(oldrev, newrev, refname)
  command = "git merge-base #{oldrev} #{newrev}"
  puts command
  system command

  line('oldrev')
  command = "git rev-list #{oldrev}"
  line command
  system command

  line('newrev')
  command = "git rev-list #{newrev}"
  line command
  system command

  line('oldrev ^newrev')
  command = "git rev-list #{oldrev} ^#{newrev}"
  line command
  system command

  line('^oldrev newrev')
  command = "git rev-list ^#{oldrev} #{newrev}"
  line command
  system command

  # puts "oldrev=#{oldrev}"
  # puts "newrev=#{newrev}"
  # puts "refname=#{refname}"

  # puts '-' * 80
  # # puts `git rev-list #{oldrev}`

  # puts '-' * 80
  # # puts `git rev-list master | grep $(git rev-parse master@{1})`
end

while line = STDIN.gets
  oldrev, newrev, refname = line.strip.split(/ /)
  show(oldrev, newrev, refname)
end



